export default {
  FETCH_POPULAR_VIDEO: "FETCH_POPULAR_VIDEO",
  FETCH_KEYWORD_VIDEO: "FETCH_KEYWORD_VIDEO",
  FETCH_VIDEO: "FETCH_VIDEO",
  FETCH_RELATED_VIDEO: "FETCH_RELATED_VIDEO",
  FETCH_CHENNEL: "FETCH_CHENNEL",
};
